insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (1, 'Dwain Joblin', 'Senior Quality Engineer');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (2, 'Hilarius Giocannoni', 'Engineer IV');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (3, 'Obadias Minister', 'Senior Sales Associate');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (4, 'Kirbie Emmanuel', 'Programmer Analyst II');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (5, 'Chloette Jeroch', 'Occupational Therapist');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (6, 'Caresa I''anson', 'Nuclear Power Engineer');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (7, 'Rochelle Maudson', 'Research Associate');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (8, 'Annabela Tylor', 'Payment Adjustment Coordinator');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (9, 'Gwenny Hearst', 'Accounting Assistant IV');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (10, 'Martica Parrett', 'Financial Analyst');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (11, 'Hubert Annion', 'GIS Technical Architect');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (12, 'Cassy Bonett', 'Senior Quality Engineer');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (13, 'Isadora Miere', 'Occupational Therapist');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (14, 'Bondie Ebben', 'Financial Advisor');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (15, 'Eryn Palia', 'Senior Cost Accountant');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (16, 'Glenine Caddan', 'Marketing Assistant');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (17, 'Michal Alpine', 'Pharmacist');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (18, 'Elwood MacFall', 'General Manager');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (19, 'Remington Robillart', 'Product Engineer');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (20, 'Rubin Brunton', 'Programmer Analyst IV');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (21, 'Matti Crebo', 'Assistant Manager');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (22, 'Ursula Hulcoop', 'Recruiting Manager');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (23, 'Holden Quarry', 'Accountant IV');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (24, 'Cacilie Backen', 'Junior Executive');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (25, 'Mozes Benzi', 'Actuary');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (26, 'Annabell Leaney', 'Design Engineer');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (27, 'Rabbi Heamus', 'Assistant Media Planner');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (28, 'Gill Haruard', 'Operator');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (29, 'Taddeusz Twentyman', 'Financial Advisor');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (30, 'Allen Littlekit', 'Senior Quality Engineer');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (31, 'Rosene Stellin', 'VP Quality Control');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (32, 'Bradan Frisby', 'Dental Hygienist');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (33, 'Latashia Slayford', 'Graphic Designer');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (34, 'Franzen Vido', 'Registered Nurse');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (35, 'Mala Nott', 'Database Administrator I');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (36, 'Kym Osbourne', 'Assistant Manager');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (37, 'Celie MacGilfoyle', 'Operator');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (38, 'Lancelot O''Heneghan', 'Developer IV');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (39, 'Dredi Maxfield', 'Community Outreach Specialist');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (40, 'Sindee Faire', 'Technical Writer');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (41, 'Gamaliel Lamminam', 'Account Representative II');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (42, 'Roxane Cobley', 'Computer Systems Analyst IV');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (43, 'Glyn Webberley', 'Quality Control Specialist');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (44, 'Fifine Warder', 'Chemical Engineer');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (45, 'Eolanda McGinlay', 'Senior Cost Accountant');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (46, 'Lotte Daintith', 'Information Systems Manager');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (47, 'Nessie Pevreal', 'Developer IV');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (48, 'Daron McSorley', 'Registered Nurse');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (49, 'Sawyere Karlik', 'Dental Hygienist');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (50, 'Vanya Chatband', 'VP Marketing');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (51, 'Teriann Yewen', 'VP Product Management');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (52, 'Earlie Hosby', 'Programmer Analyst IV');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (53, 'Thibaud Papierz', 'Chief Design Engineer');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (54, 'Corby Cockshtt', 'Desktop Support Technician');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (55, 'Querida Erbe', 'Account Coordinator');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (56, 'Barb Mc Pake', 'Nurse Practicioner');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (57, 'Linoel Scud', 'Programmer Analyst III');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (58, 'Kara Derell', 'Data Coordinator');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (59, 'Nari Gianasi', 'Graphic Designer');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (60, 'Una Moores', 'Help Desk Operator');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (61, 'Sissie Mitchelson', 'Financial Advisor');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (62, 'Ruthanne Falla', 'Executive Secretary');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (63, 'Kristoforo Milley', 'Recruiting Manager');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (64, 'Pinchas Peyntue', 'Director of Sales');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (65, 'Nikolaus Jeandon', 'Operator');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (66, 'Sophronia Blunkett', 'Human Resources Assistant I');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (67, 'Silvano Geard', 'Electrical Engineer');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (68, 'Mitch Emson', 'Compensation Analyst');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (69, 'Ana Dowsett', 'Technical Writer');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (70, 'Vaclav Riddiough', 'Web Designer II');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (71, 'Chucho Starrs', 'VP Product Management');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (72, 'Daphene Hunstone', 'Administrative Officer');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (73, 'Gusty Hadcroft', 'Food Chemist');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (74, 'Pippa Rignall', 'Media Manager III');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (75, 'Theodora Maryon', 'VP Marketing');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (76, 'Iona Whilde', 'Assistant Professor');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (77, 'Rodd Kissock', 'Speech Pathologist');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (78, 'Terrill Aymes', 'Design Engineer');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (79, 'Devinne Jearum', 'General Manager');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (80, 'Clotilda Skade', 'Software Engineer III');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (81, 'Reuben Gocke', 'Design Engineer');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (82, 'Michal Yard', 'Accounting Assistant I');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (83, 'Johnathan Pagelsen', 'Food Chemist');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (84, 'Patrizia Ville', 'Desktop Support Technician');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (85, 'Ameline Bichener', 'Recruiting Manager');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (86, 'Cinda Dryden', 'Data Coordinator');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (87, 'Blair Lamers', 'VP Sales');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (88, 'Esra Bathurst', 'Senior Financial Analyst');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (89, 'Hannah Edden', 'Budget/Accounting Analyst II');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (90, 'Myrta Oades', 'Recruiter');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (91, 'Monika Goalley', 'Systems Administrator IV');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (92, 'Priscella MacGillivrie', 'Help Desk Technician');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (93, 'Randie Lucey', 'Developer I');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (94, 'Trisha Pohlak', 'Electrical Engineer');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (95, 'Johann Harmstone', 'Nurse Practicioner');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (96, 'Cori Ritchie', 'Occupational Therapist');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (97, 'Aleda Bysouth', 'Senior Quality Engineer');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (98, 'Markus Hullyer', 'Recruiting Manager');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (99, 'Margaux Caldecot', 'Statistician I');
insert into Funcionarios (matriculaFuncionario, nomeFuncionario, cargoFuncionario) values (100, 'Abe O''Ferris', 'Assistant Professor');
