insert into Funcionarios (nomeFuncionario, cargoFuncionario) values ('May Eich', 'balconista');
insert into Funcionarios (nomeFuncionario, cargoFuncionario) values ('Almeria Brelsford', 'recepcionista');
insert into Funcionarios (nomeFuncionario, cargoFuncionario) values ('Nina Heaps', 'balconista');
insert into Funcionarios (nomeFuncionario, cargoFuncionario) values ('Austine Dorre', 'garçom');
insert into Funcionarios (nomeFuncionario, cargoFuncionario) values ('Emmott Snoxall', 'recepcionista');
insert into Funcionarios (nomeFuncionario, cargoFuncionario) values ('Ed Goulder', 'recepcionista');
insert into Funcionarios (nomeFuncionario, cargoFuncionario) values ('Valerye Osichev', 'gerente');
insert into Funcionarios (nomeFuncionario, cargoFuncionario) values ('Beatrisa Taffe', 'balconista');
insert into Funcionarios (nomeFuncionario, cargoFuncionario) values ('Sandye Pache', 'gerente');
insert into Funcionarios (nomeFuncionario, cargoFuncionario) values ('Valry Tomadoni', 'gerente');
insert into Funcionarios (nomeFuncionario, cargoFuncionario) values ('Cassey Tyreman', 'recepcionista');
insert into Funcionarios (nomeFuncionario, cargoFuncionario) values ('Klarika Dog', 'recepcionista');
insert into Funcionarios (nomeFuncionario, cargoFuncionario) values ('Vick Josephson', 'gerente');
insert into Funcionarios (nomeFuncionario, cargoFuncionario) values ('Lucine Fitch', 'balconista');
insert into Funcionarios (nomeFuncionario, cargoFuncionario) values ('Geoffrey Tytcomb', 'gerente');
insert into Funcionarios (nomeFuncionario, cargoFuncionario) values ('Lurlene Heineking', 'garçom');
insert into Funcionarios (nomeFuncionario, cargoFuncionario) values ('Franky Lilburn', 'garçom');
insert into Funcionarios (nomeFuncionario, cargoFuncionario) values ('Viviana Janse', 'garçom');
insert into Funcionarios (nomeFuncionario, cargoFuncionario) values ('Kacey Meadowcroft', 'garçom');
insert into Funcionarios (nomeFuncionario, cargoFuncionario) values ('Adria Longhorne', 'garçom');

SELECT * FROM Funcionarios;