insert into Produtos (nomeProduto, descricaoProduto, precoProduto) values ('Espresso', 'hac habitasse platea dictumst', 15.5);
insert into Produtos (nomeProduto, descricaoProduto, precoProduto) values ('Machiato', 'turpis elementum ligula vehicula consequat morbi a', 19.46);
insert into Produtos (nomeProduto, descricaoProduto, precoProduto) values ('Mocha', 'parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor', 5.98);
insert into Produtos (nomeProduto, descricaoProduto, precoProduto) values ('Americano', 'pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et', 16.84);
insert into Produtos (nomeProduto, descricaoProduto, precoProduto) values ('Capuccino', 'posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit', 22.87);
insert into Produtos (nomeProduto, descricaoProduto, precoProduto) values ('Frappe', 'velit id pretium iaculis diam erat fermentum justo', 15.18);
insert into Produtos (nomeProduto, descricaoProduto, precoProduto) values ('Croissant', 'nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque', 22.05);
insert into Produtos (nomeProduto, descricaoProduto, precoProduto) values ('Donut', 'duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec', 9.99);
insert into Produtos (nomeProduto, descricaoProduto, precoProduto) values ('Pão de Queijo', 'integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam', 12.03);
insert into Produtos (nomeProduto, descricaoProduto, precoProduto) values ('Esfirra', 'in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate', 9.4);
insert into Produtos (nomeProduto, descricaoProduto, precoProduto) values ('Coxinha', 'vitae nisl aenean lectus pellentesque eget', 6.94);
insert into Produtos (nomeProduto, descricaoProduto, precoProduto) values ('Empada', 'lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus', 11.5);
insert into Produtos (nomeProduto, descricaoProduto, precoProduto) values ('Pastel de Queijo', 'quis turpis eget', 7.99);
insert into Produtos (nomeProduto, descricaoProduto, precoProduto) values ('Pastel de Frango', 'at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes', 9.09);
insert into Produtos (nomeProduto, descricaoProduto, precoProduto) values ('Sanduíche Natural', 'pellentesque viverra pede ac diam cras pellentesque volutpat dui', 3.54);
insert into Produtos (nomeProduto, descricaoProduto, precoProduto) values ('Bauru', 'quam pede', 11.7);
insert into Produtos (nomeProduto, descricaoProduto, precoProduto) values ('Cheeseburguer', 'vestibulum vestibulum ante ipsum primis in faucibus orci', 16.95);
insert into Produtos (nomeProduto, descricaoProduto, precoProduto) values ('Pão com Queijo', 'ac neque', 9.63);

SELECT * FROM Produtos;